# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.1
  - 1.4
  - nightly
notifications:
  email: false

script: # the default script is equivalent to the following ()
        # I added DayCounts as an import here to avoid adding a dependency
        # just for doctests
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --project -e 'using Pkg; Pkg.add("DayCounts"); Pkg.build(); Pkg.test(; coverage=true)';
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
